project:
  type: website
  output-dir: ../public

website:
  title: "Forecast Research"
  navbar:
    title: "Research"
    logo: /img/wordmark.svg
    
    # right:
    #   - href: index.qmd
    #     text: Home
    #   - about.qmd

format:
  html:
    theme:
      - pandoc
      - brand
      - theme-light.scss
    css: styles.css
    toc: true
    toc-location: left
    toc-title: "OpenAstrocytes"
    include-in-header:
    - text: |
        <style>
        .navbar-logo {
          max-height: unset;
          height: 18px;
          margin-top: -1px;
        }
        .navbar-brand {
          margin-top: 6px;
        }
        .navbar-title {
          color: #F95838;
          font-size: 18pt;
          font-family: 'Times New Roman';
          font-style: italic
        }
        </style>


#