project:
  type: website
  output-dir: ../public

website:
  title: "Forecast Research"
  navbar: {}
    # right:
    #   - href: index.qmd
    #     text: Home
    #   - about.qmd

format:
  html:
    theme:
      - pandoc
      - brand
      - theme-light.scss
    css: styles.css
    toc: true
    toc-title: "OpenAstrocytes"


#